### ISSUE TITLE
Refactoring launcher

### ISSUE THREAD

**Issue by fmahiant** [RaspInLoop/RaspInLoop-fmi-plugin#11]
Launcher is a java application used to communicate with eclipse (debug plugin) and to run the real application (code to debug).
Launcher uses JavaAgent to perform code weavering. This allows Thread.sleep (and equivalent) to be replaced by classes driven by the simulation tool.
JavaAgent should also be used in place of launcher application. So the debug plugin will just have to launch the real application with an agent uses to replace some part of code (IO lib call) by our.

**Comment by zroll** [comment]
Hello, I've seen you were looking for help. Mind if I look into this task?  Any suggestions will be highly appreciated.

**Comment by fmahiant** [comment]
Hello,

Of course,your help is welcome..

I've already started some refactoring in this way...(separate eclipse
plugin code and raspinloop code to be able to build plugin for other dev
tools)
So I still have to commit it in the RunnerAgent branch.

There is a lot a work in this task, so, I will happy to guide you. By the
way, by which facet of this project are more interested?

   - JavaAgent, code weavering, AOP
   - Plugin for development tool (Eclipse, IntelliJ IDEA, ...)
   - Simulation tool (matlab, scilab), model, FMU/FMI)
   - UnitTesting ? (there is a lack of unit testing in this project)
   - other ? ;-)

So, I will stabilize my work,, I will commit it and I will be back with
more details.

Regards,

Fred.

**Comment by zroll** [comment]
Hello,

thank you for the reply. I would say that a good start would be starting with UTs, to understand the usage of different parts and afterwards see where more things to be done. 

What do you think?

Olimpiu

**Comment by fmahiant** [comment]
Hi,
I've just committing my latest change to make the code runnable. 
Changes consists in separate IDE plugin code to launcher and agent code.
To summarize, we have now a bunch of code responsible to communicate with the simulated FMU, start the program to debug (via an javaagent) and to "proxify" the FMU command to the agent.

I've done some test with FMPy as simulation tool. see https://github.com/RaspInLoop/RaspInLoop-fmi-plugin/wiki/using-FMPy 

The code is pushed in RunnerAgent's branch

I'm sure thre is a lot of thing to explaing, document, etc... do not hesitate to ask for more information. 

Fred.

**Comment by fmahiant** [comment]
Hi, This Issue (the launcher refactoring) is now close (modification are now merged in master).
Nevertheless, there is a lot of missing UT in this part. or in the Eclispe Plugin part.
There  are also a lot of device/borad  to  simulate.
I may write some in depth documentation for your selected part of the project ;-)

Fred.
